### ISSUE TITLE
支持rtmp回源穿透认证

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs#104]
https://github.com/winlinvip/simple-rtmp-server/issues/104

**Comment by walkermi** [comment]
@winlinvip Many of the old issue links are no longer valid, what a pity!

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Hehe, you can check WIKI, RTMP back-to-origin penetration authentication means that the edge will authenticate each connection back to the origin once.
Actually, this authentication is more suitable to be implemented with HTTP callback.

`TRANS_BY_GPT3`
