### ISSUE TITLE
输出HLS时，支持RTMP包中的AnnexB格式

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs#184]
https://github.com/winlinvip/simple-rtmp-server/issues/184

**Comment by winlinvip** [comment]
In theory, RTMP should be in IBMF format, but sometimes it may also have annexb. SRS will detect the content format.

`TRANS_BY_GPT3`

**Comment by b04505009** [comment]
Hi, I would like to ask that where can I find the info of "RTMP should be in IBMF format", and is there an easy way to check that if my rtmp stream is IBMF or AnnexB? Thanks!
