### ISSUE TITLE
srslibrtmp send packet before sps/pps(sequence header) which disabled hls #203

### ISSUE THREAD

**Issue by xxxman2008** [simple-rtmp-server/srs#203]
https://github.com/winlinvip/simple-rtmp-server/issues/203

**Comment by onvejon** [comment]
https://github.com/winlinvip/simple-rtmp-server/issues/203
很多重要的 issues url 不可访问了，想看看问题的详细描述请问怎样处理。

**Comment by winlinvip** [comment]
低号段的issue丢失了，高号段的还在。
