### ISSUE TITLE
视频源RTMP推流停止后，对应的HLS文件m3u8、ts能否清理掉？ #209

### ISSUE THREAD

**Issue by xxxman2008** [simple-rtmp-server/srs#209]
https://github.com/winlinvip/simple-rtmp-server/issues/209

**Comment by winlinvip** [comment]
The cessation of RTMP streams does not necessarily mean the termination of the service. However, there are two situations in which cleaning can be done:
1. Files can be cleaned after a certain period of time when the RTMP stream stops.
2. When the server stops.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
```
        # the timeout in seconds to dispose the hls,
        # dispose is to remove all hls files, m3u8 and ts files.
        # when timeout or server terminate, dispose hls.
        # default: 300
        hls_dispose     300;
```


Add a new option to set the timeout for HLS, with a default value of 5 minutes. If there is no stream for 5 minutes, all existing HLS files will be cleared.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
When the server stops, clean up HLS segments.
```
winlin:srs winlin$ ll objs/nginx/html/live/livestream
total 1784
-rw-r--r--  1 winlin  staff  576784 May 30 13:38 1432964311500.ts
-rw-r--r--  1 winlin  staff  330880 May 30 13:38 1432964326198.ts.tmp
-rw-r--r--  1 winlin  staff     159 May 30 13:38 live.m3u8
winlin:srs winlin$ time ./etc/init.d/srs stop
Stopping SRS(pid 13213)...                                 [  OK  ]
SRS stopped by SIGTERM                                     [  OK  ]


real    0m0.470s
user    0m0.035s
sys 0m0.049s
winlin:srs winlin$ ll objs/nginx/html/live/livestream
winlin:srs winlin$ 
```

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Already resolved. Restart and clean up HLS when there is no flow timeout.

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
Which version of the code added the mechanism to delete HLS? I downloaded the develop code and restarted, but it still doesn't work. The configuration should be correct, right?
![image](https://cloud.githubusercontent.com/assets/11712819/18948780/0c761656-866b-11e6-95e4-e06342a7d052.png)

`TRANS_BY_GPT3`

**Comment by xiayongtao** [comment]
![image](https://cloud.githubusercontent.com/assets/11712819/18948793/1a834ad4-866b-11e6-92ed-075d2d5097bc.png)
