### ISSUE TITLE
fill the chunk packet to make the recv thread to guess the chunk stream

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs#241]
https://github.com/winlinvip/simple-rtmp-server/pull/240

**Comment by owenchzh** [comment]
rtmp 发送H264数据，每帧发送，到结束，平均要20ms左右的时间，请问出现这个情况是为什么

**Comment by FreshLuoBoGan** [comment]
目前，我相机RTMFP推流到SRS，通过VLC获取SRS视频。用conf中的最低延迟配置，在最初的5分钟内，延时为5秒，5分钟内，延时逐渐降低，5分钟后，延时降到1s。这个应该如何去查找问题？（使用的是min.delay.com配置）
