### ISSUE TITLE
HTTP API kick/redirect client

### ISSUE THREAD

**Issue by misiek08** [simple-rtmp-server/srs#406]
One of the most needed features right now is kicking or redirecting client by http request. Look at nginx-rtmp-module's control module (*Drop and Redirect* methods: [nginx-rtmp wiki](https://github.com/arut/nginx-rtmp-module/wiki/Control-module)). I think that's one of last things that are missing.

We are missing many http hooks for dvr, hls, but nginx doesn't have them too, so it's future feature request.

**Comment by winlinvip** [comment]
Seems the control module is great.

**Comment by misiek08** [comment]
Drop part should be easy, redirect is propably much harder to implement, but for me it's last must have that isn't present in SRS.

**Comment by winlinvip** [comment]
Redirect is very easy, while drop connection is not easy.

**Comment by mvberg** [comment]
Send them a 504 :)

**Comment by misiek08** [comment]
Drop can be done as just closing socket and doing same cleanup like for
client exit, can't it?

2015-05-25 2:48 GMT+02:00 Mike Ehrenberg <notifications@github.com>:

> Send them a 504 :)

**Comment by winlinvip** [comment]
I think this bug should be split to two:
1. kickoff connection.
2. redirect connection.

**Comment by winlinvip** [comment]
I close this one, and anyone who wants this feature, please track the #442 and #443
