### ISSUE TITLE
srs 2.0 compile fail with parameter: --disable-all --with-ssl && make

### ISSUE THREAD

**Issue by szahlfors** [simple-rtmp-server/srs#407]
when download 2.0 source code and compile with low latency as wiki description:
./configure --disable-all --with-ssl && make 
it will show following error:
in file included from src/app/srs_app_server.cpp:24:0:
src/app/srs_app_server.hpp:234:22: error: invalid use of incomplete type ‘class ISrsHlsHandler’
     , virtual public IConnectionManager
                      ^
In file included from src/app/srs_app_server.hpp:38:0,
                 from src/app/srs_app_server.cpp:24:
src/app/srs_app_source.hpp:64:7: error: forward declaration of ‘class ISrsHlsHandler’
 class ISrsHlsHandler;
       ^
objs/Makefile:144: recipe for target 'objs/src/app/srs_app_server.o' failed

**Comment by winlinvip** [comment]
禁用HLS后的编译错误，我会fix它的。

**Comment by winlinvip** [comment]
fixed
