### ISSUE TITLE
SRS2： 同一直播流，编码器重新推送后，HLS第一次正常，再次就异常  

### ISSUE THREAD

**Issue by davidshen1234** [simple-rtmp-server/srs#414]
编码器推送rtmp直播流，当编码器断开连接，重新推送该流，HLS第一次正常，再次就异常 。发现此时在hls_path/live 目录下，并不会循环生成ts文件，而是一直在写最后一个文件 stream1-11355.ts.tmp，而m3u8文件此时也不会更新。

此问题较#280有改善，但没彻底解决（#280 SRS1 编码器重推后，HLS第一次都不正常）

**Comment by winlinvip** [comment]
When submitting a bug or asking a question, please provide the following information:

- System: What operating system? 32-bit or 64-bit? Compiler version?
- Encoder: What encoder are you using? What version? What are the encoding parameters? What is the stream address?
- Server: What version of SRS are you using? What is the configuration? What are the logs?
- Client: What client are you using? What version?
- Issue and Reproduction Steps: What is the issue? What are the steps to reproduce it?

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
System: cent6.6 64-bit gcc 4.4.7

Encoder: Self-made, encoding: H264+AAC, see details at: http://www.tongshi.com/products_8.html

Server: SRS version: 2.0 release, configuration: using the built-in hls.conf, log: 7MB, unsure how to upload?

Client: Client: vlc 2.1.5

Issue and Reproduction Steps: When the encoder pushes an rtmp live stream and then disconnects and pushes the stream again, the HLS works fine the first time but becomes abnormal on subsequent pushes. It is noticed that in the hls_path/live directory, instead of generating ts files in a loop, it keeps writing to the last file stream1-11355.ts.tmp, and the m3u8 file is not updated at this time.

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
Hello!

   Please see the attached LOG information.


2015-05-30 


Shenxuefeng 


Sender: winlin
Sent: 2015-05-30 10:20:38
Recipient: simple-rtmp-server/srs
CC: davidshen1234
Subject: Re: [srs] SRS2: HLS abnormal after encoder re-push (#414)

When submitting a bug or asking a question, please provide the following information:
System: What operating system? 32-bit or 64-bit? Compiler version?
Encoder: What encoder are you using? What version? What are the encoding parameters? What is the stream address?
Server: What version of SRS are you using? What is the configuration? What are the logs?
Client: What client are you using? What version?
Issue and Reproduction Steps: What is the issue? What are the steps to reproduce it?
—
Reply to this email directly or view it on GitHub.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It is possible that the failure to interpret the SRS data of the encoder caused this. I will find time to examine the logs in detail.
You can try to see if you can bypass it; at the same time, I will fix this issue. Configure the encoder to reconnect when HLS parsing fails.
```
hls {
        # the error strategy. canbe:
        #       ignore, when error ignore and disable hls.
        #       disconnect, when error disconnect the publish connection.
        #       continue, when error ignore and continue output hls.
        # @see https://github.com/simple-rtmp-server/srs/issues/264
        # default: ignore
        hls_on_error    disconnect;
}
```

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
We tried adding 'hls_on_error disconnect;' but there was no change in the result.
Note: Our encoder output stream is monotonic for both video and audio, not just the stream. This was modified in SRS2. I wonder if this is the reason for the HLS reconnection error?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Oh, in order to ensure incremental separation, you need to activate another option to make SRS guarantee mixed incremental separation.
```
    # whether use the interleaved/mixed algorithm to correct the timestamp.
    # if on, always ensure the timestamp of audio+video is interleaved/mixed monotonically increase.
    # if off, use time_jitter to correct the timestamp if required.
    # default: off
    mix_correct             on;
```

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
Our specific modifications are as follows:
1. Modify the default jitter to zero in the src/app/srs_app_config.hpp file.
2. In the on_audio() and on_video() functions in the src/app/srs_app_hls.cpp file, change the parameter of the jitter->correct() function to SrsRtmpJitterAlgorithmZERO.

After adding the two configurations you mentioned, the result remains unchanged.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
1. timejitter is a timestamp correction algorithm that can be modified in the configuration without changing the code.
2. mix_correct is a mixed incremental algorithm that solves the problem of audio and video mixing increment.
3. hls_on_error is an error handling feature that allows the encoder to reconnect when there is an HLS error.

If none of these work, then we will have to find a weekend for you to push to the server I specified, and I will debug to see what the problem is.

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
Okay, I'm not sure if you're available for debugging this weekend (June 6th) at 10 AM.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Saturday at 10 might be too early, how about 11 o'clock? Add me on QQ to contact me.

`TRANS_BY_GPT3`

**Comment by davidshen1234** [comment]
Okay, He Gong, who is specifically in charge of this project, will come down and communicate with you directly.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Enable hybrid incremental algorithm to correct timestamps:


```
vhost xxx {
     mix_correct on;
}
```

`TRANS_BY_GPT3`
