### ISSUE TITLE
Server crash when trying to open non-existent stream (2.0.173)

### ISSUE THREAD

**Issue by icevl** [simple-rtmp-server/srs#416]
When i trying to open RTMP non-existent stream, SRS daemon is crash .

SRS version: 2.0.173
```
Example: rtmp://server:1935/live?vhost=__defaultVhost__/streamnonexistenthere
```

**Comment by winlinvip** [comment]
Seems bug introduced by SRS 2, I will fix it ASAP.

**Comment by winlinvip** [comment]
Fix it by: https://github.com/simple-rtmp-server/srs/commit/4e42b9c6286bd8483d8736803506ab5ec0b2a788
