### ISSUE TITLE
Fresh install, demo > "/live/demo.1433257811190.m3u8" not found

### ISSUE THREAD

**Issue by ebuildy** [simple-rtmp-server/srs#417]
Hello, not sure it's a bug, but I have just installed SRS (perfectly fine by the way !), then I play with the demo, I can easily use my webcam to stream via RTMP but, when I click on HLS:

    /live/demo.1433257811190.m3u8 Not Found

**Comment by winlinvip** [comment]
What is your version of SRS?
Please try SRS1, the release SRS.

**Comment by ebuildy** [comment]
Hello, thanks for the fast answer. I did a checkout to 1.0release, run again:

http://beemapp.me/view/fc9a52df-beea-4155-9510-7ccc187a2c50

But same thing, maybe I need to so something in the config. ?

Thanks,

**Comment by winlinvip** [comment]
Did you follow this guide step by step? https://github.com/simple-rtmp-server/srs/wiki/v1_EN_SampleDemo

**Comment by winlinvip** [comment]
U should follow the wiki guide, the media stream system is complex.
