### ISSUE TITLE
 hls only support video h.264/avc

### ISSUE THREAD

**Issue by abanger** [simple-rtmp-server/srs#422]
[2015-06-08 18:00:00.458][error][13797][107][11] hls only support video h.264/avc codec. actual=2, ret=3001(Resource temporarily unavailable)
[2015-06-08 18:00:00.458][error][13797][107][11] hls codec demux video failed. ret=3001(Resource temporarily unavailable)
[2015-06-08 18:00:00.458][warn][13797][107][11] hls process video message failed, ignore and disable hls. ret=3001

# main config for srs.
# @see full.conf for detail config.

listen              1935;
max_connections     1000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_stream {
    enabled         on;
    listen          80;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_path        ./objs/nginx/html;
        hls_fragment    10;
        hls_window      60;
    }

}

**Comment by winlinvip** [comment]
1. never use full.conf, please follow the guide of SRS.  https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Setup or https://github.com/simple-rtmp-server/srs/wiki/v2_CN_Setup
1. HLS only supports h.264, your codec is not h.264?

**Comment by winlinvip** [comment]
1. Please follow the guide of SRS.  https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Setup or https://github.com/simple-rtmp-server/srs/wiki/v2_CN_Setup
1. HLS only supports h.264, your codec is not h.264?
