### ISSUE TITLE
start ingest stream on connect 

### ISSUE THREAD

**Issue by khaledeltaib** [simple-rtmp-server/srs#426]
are it possible to start ingest stream transcode on connect and stop it on close like pull ?

**Comment by winlinvip** [comment]
Use http hooks to start ffmpeg when got on_connect event.

**Comment by khaledeltaib** [comment]
thanks .
on_connect
{
    "action": "on_connect",
    "client_id": 1985,
    "ip": "192.168.1.10", "vhost": "video.test.com", 
    "app": "live",
    "tcUrl": "rtmp://video.test.com/live?key=xxx",
    "pageUrl": "http://www.test.com/live.html"
}
still dose not know stream name yet to start transcode but can fix use ?key=xxx
so i will do ..
..
haw to do smart stop for transcode when last client disconnect ?

**Comment by khaledeltaib** [comment]
are this format can support by srs 

    ingest [stream] {
        enabled      on;
        input {
            type    stream;
            url     http://TV.mine.nu/live/[stream];
        }
        ffmpeg      /usr/local/bin/ffmpeg;
        engine {
            enabled          off;
            output          rtmp://127.0.0.1:[port]/[app]?vhost=[vhost]/[stream];
			
        }
    }
so start transcode from different source at play time only and stop transcode when disconnect

**Comment by winlinvip** [comment]
Nop, u must use http hooks, not the ingest.
Client ==play==>  SRS   ==http=hooks==>  YourSystem  ==start=ffmpeg==>   SRS

These two SRS can be the same one.

**Comment by khaledeltaib** [comment]
ok thanks .do you have good idea for termination ffmpeg process. When publisher closes the stream? and last client view stream close also.
so need
??== SRS ==http=hooks==> mySystem ==stop=ffmpeg
thanks

**Comment by winlinvip** [comment]
Yep, your system must know whether the client is the last one when on_close hooks invoked, or u can query the http api of SRS to check whether there  is no clients playing stream.
When u got the last client close event by hook the `on_close`, u can send SIG_TERM to FFMPEG, then wait about some seconds for FFMPEG to quit gracefully, when timeout send SIG_KILL to FFMPEG to force FFMEPG to quit to avoid it not quit.

**Comment by khaledeltaib** [comment]
thanks for help .. i will try to query the http api of SRS to check whether there is no clients playing stream
