### ISSUE TITLE
编译2.0 arm版本的时候./configure出错。编译st库出错。

### ISSUE THREAD

**Issue by daozhao** [simple-rtmp-server/srs#428]
~/srs/trunk# ./configure --with-arm-ubuntu12
/bin/bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
regenerate config: --prefix=/usr/local/srs --with-hls --with-hds --with-dvr --without-nginx --with-ssl --without-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --without-stream-caster --with-http-api --with-librtmp --without-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --with-arm-ubuntu12 --without-mips-ubuntu12 --static --log-trace
check gcc/g++/gdb/make
depends tools are ok
install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi
Reading package lists... Done
Building dependency tree
Reading state information... Done
g++-arm-linux-gnueabi is already the newest version.
gcc-arm-linux-gnueabi is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
install gcc-arm-linux-gnueabi g++-arm-linux-gnueabi success
Ubuntu detected, install tools if needed
Ubuntu install tools success
build st-1.9t for arm
patching file md.h
patching file io.c
patching file Makefile
make OS="LINUX" BUILD="DBG"
make[1]: Entering directory `/root/srs/trunk/objs/st-1.9'
if [ ! -d LINUX_3.13.0-24-generic_DBG ]; then mkdir LINUX_3.13.0-24-generic_DBG; fi
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c sched.c -o LINUX_3.13.0-24-generic_DBG/sched.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/sched.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c stk.c -o LINUX_3.13.0-24-generic_DBG/stk.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/stk.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c sync.c -o LINUX_3.13.0-24-generic_DBG/sync.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/sync.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c key.c -o LINUX_3.13.0-24-generic_DBG/key.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/key.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c io.c -o LINUX_3.13.0-24-generic_DBG/io.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/io.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c event.c -o LINUX_3.13.0-24-generic_DBG/event.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/event.o] Error 127 (ignored)
DLINUX -DDEBUG -Wall -g -DMD_HAVE_EPOLL -c md.S -o LINUX_3.13.0-24-generic_DBG/md.o
make[1]: DLINUX: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/md.o] Error 127 (ignored)
rv LINUX_3.13.0-24-generic_DBG/libst.a LINUX_3.13.0-24-generic_DBG/sched.o LINUX_3.13.0-24-generic_DBG/stk.o LINUX_3.13.0-24-generic_DBG/sync.o LINUX_3.13.0-24-generic_DBG/key.o LINUX_3.13.0-24-generic_DBG/io.o LINUX_3.13.0-24-generic_DBG/event.o LINUX_3.13.0-24-generic_DBG/md.o
make[1]: rv: Command not found
make[1]: [LINUX_3.13.0-24-generic_DBG/libst.a] Error 127 (ignored)
ranlib LINUX_3.13.0-24-generic_DBG/libst.a
ranlib: 'LINUX_3.13.0-24-generic_DBG/libst.a': No such file
make[1]: *** [LINUX_3.13.0-24-generic_DBG/libst.a] Error 1
make[1]: Leaving directory `/root/srs/trunk/objs/st-1.9'
make: *** [linux-debug] Error 2
build st-1.9 failed, ret=2

**Comment by winlinvip** [comment]
提交bug，或者问问题时，说明以下情况：
* 系统：什么操作系统？32位还是64位？编译器版本多少？
* 编码器：用什么编码器？版本是什么？编码参数是什么？流地址是什么？
* 服务器：用SRS什么版本？配置是什么？日志是什么？
* 客户端：用什么客户端？版本是什么？
* 问题和重现步骤：问题是什么？重现步骤是什么？

**Comment by daozhao** [comment]
系统：什么操作系统？32位还是64位？编译器版本多少？
Ubuntu 64位。12.04.5 arm-linux-gnueabi-gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)
编译环境使用此[docker](https://registry.hub.docker.com/u/daozhao/armv7-toolchain/)进行编译。

srs版本 srs 2.0 release   commit 2e437a28b4b8d4bc46b9a48ebfcb276aeb5bb2ab

**Comment by winlinvip** [comment]
I will fix this.

**Comment by winlinvip** [comment]
read #485
