### ISSUE TITLE
ACL for input stream

### ISSUE THREAD

**Issue by madorin** [simple-rtmp-server/srs#430]
I'd like to have configuration options like ip/domain to accept/filter input streams.

**Comment by winlinvip** [comment]
For SRS2, u can use security, please read https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Security

**Comment by madorin** [comment]
Ah, thanks!
I didn't saw there is also 2.0 version. Installed from 1.x branch.
Good-luck, great project!
