### ISSUE TITLE
Linux directories

### ISSUE THREAD

**Issue by madorin** [simple-rtmp-server/srs#431]
For Linux distros (at least Debian, Ubuntu), use linux-way default directories:
/etc/srs for configuration
/var/log/srs for logging
/var/run/srs for process files
/usr/sbin for executables

**Comment by winlinvip** [comment]
SRS use /usr/local/srs as default main directory, and other files default to relative directory, for instance, config default to ./conf/srs.conf, log default to ./objs/srs.log, pid file default to ./objs/srs.pid, binary default to ./objs/srs. The relative directory structure enable us to start many SRS processes, without access permission issues.
However, SRS support other directoty structure, you can write the install script for Debian and Ubuntu, by specifying the config/log/pid in config.
