### ISSUE TITLE
HLS纯音频无法播放

### ISSUE THREAD

**Issue by zhao-xiang** [simple-rtmp-server/srs#434]
srs2.0，使用ffmpeg加-vn选项推rtmp单音频流，SRS转成HLS发布后无法播放

**Comment by winlinvip** [comment]
I will find time to take a look.

`TRANS_BY_GPT3`

**Comment by zhao-xiang** [comment]
Just saw the note on the wiki that says "Note: VLC cannot play pure audio streams, but jwplayer can." Jwplayer can play it, but VLC and the flash player I'm using cannot. Is it a problem with the player? Can it be fixed on SRS?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Oh, I remember VLC was working fine. But if both Apple and Flash are not having any issues, then it's possible that the problem lies with VLC.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
http://ossrs.net:8081/live/aonly.m3u8
VLC plays without any issues.

`TRANS_BY_GPT3`
