### ISSUE TITLE
HTTP API kickoff client

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs#442]
@see #406

**Comment by winlinvip** [comment]
Provide API to support kicking off the stream.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Usage instructions, refer to WIKI:
https://github.com/simple-rtmp-server/srs/wiki/v2_CN_Security#kickoff-client
https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Security#kickoff-client


https://github.com/simple-rtmp-server/srs/wiki/v2_CN_HTTPApi#kickoff-client
https://github.com/simple-rtmp-server/srs/wiki/v2_EN_HTTPApi#kickoff-client

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Actually, the client for live streaming should be deleted.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
This is the API for nginx, which is quite limited: https://github.com/arut/nginx-rtmp-module/wiki/Getting-number-of-subscribers
This is the kickoff/drop feature for nginx: https://github.com/arut/nginx-rtmp-module/wiki/Control-module. You can refer to the bug I submitted: #459.

`TRANS_BY_GPT3`

**Comment by chaclus** [comment]
If it is a cluster, how can we kickoff the publish client? Each node in the cluster may have the same client_id.

`TRANS_BY_GPT3`
