### ISSUE TITLE
Not able to re-stream from Nginx-RTMP to SRS

### ISSUE THREAD

**Issue by gouravd** [simple-rtmp-server/srs#449]
Hello, Congratulations for the great product. 

I am starting to experiment with this product. I currently serve my customers using RTMP module of NGINX.

1) Nginx already uses port 1935, so in srs conf I used port 19350
2) I added the following line in Nginx
exec_push /home/voolastreamer/bin/ffmpeg -i rtmp://xxx.xxx.xxx.xxx:1935/staging_infinity_live/$name -vprofile baseline -acodec copy -vcode copy -copyts -f flv rtmp://xxx.xxx.xxx.xxx:19350/live/$name 2>>/home/Videos_staging/staging_flv/$name-srs.txt

But this does not work. I am sure I am doing lot of things awefully wrong.

Question 1: I am confused as to what the proper configuration for SRS should be to allow redirecting from Nginx to SRS

Question 2: How to change the /live part in the SRS. In Nginx the app is called staging_live. How do I create a simillar app in SRS. Is VHost in SRS simillar to App in Nginx?
Question 3: In Nginx the incoming stream name varies for each stream, how to set variable stream name in SRS. 
Example:
Incoming in Nginx: rtmp://xxx.xxx.xxx.xxx:1935/staging_live/<any name>
Nginx should redirect to SRS at: rtmp://xxx.xxx.xxx.xxx:19350/staging_live/<any name>

here is my srs.conf

```
# main config for srs.
# @see full.conf for detail config.

listen              19350;
max_connections     5000;
srs_log_tank        file;
srs_log_file        ./objs/srs.log;
http_api {
    enabled         on;
    listen          1985;
}
http_stream {
    enabled         on;
    listen          8081;
    dir             ./objs/nginx/html;
}
stats {
    network         0;
    disk            sda sdb xvda xvdb;
}
vhost __defaultVhost__ {
}
```

**Comment by winlinvip** [comment]
Please show your SRS log.
About the app and vhost, read  the wiki: https://github.com/simple-rtmp-server/srs/wiki/v1_EN_RtmpUrlVhost

In a word, SRS config base on vhost which has many apps, but not like nginx-rtmp, all app for SRS is automatically create.
For your config, you can publish stream to any app of that vhost:
```
ffmpeg -re -i doc/source*.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/live/livestream
ffmpeg -re -i doc/source*.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/youapp/livestream
ffmpeg -re -i doc/source*.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/anything/livestream
ffmpeg -re -i doc/source*.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/whatever/livestream
```

SRS config base on vhost, one vhost for one customer or config instance.

**Comment by gouravd** [comment]
Found this in the first line of log
invalid max_connections=5000, system limit to 1024, ret=1023. you can login as root and set the limit: ulimit -HSn 5000(No such file or directory)

Will make the changes, try again and let you know

Regardung the "App", if I understand correctly SRS would dynamically create the "Apps" or vhosts

What about the stream name. Can I give any stream name while publishing to SRS?

**Comment by gouravd** [comment]
In Nginx, I am using the following

exec_push /home/voolastreamer/bin/ffmpeg -re -i rtmp://xxx.xxx.xxx.xxx:1935/staging_infinity_live/$name -vprofile baseline -acodec copy -vcodec copy -copyts -f flv -y rtmp://127.0.0.1:19350/live/$name 2>>/home/Videos_staging/staging_flv/$name-srs.txt

The log ffmpeg generated log file is empty, so I assume its not pushing to rtmp://127.0.0.1:19350

In srs.log, I keep getting these messages

RTMP client ip=127.0.0.1
[2015-07-30 07:43:46.535][trace][5858][111] complex handshake success
[2015-07-30 07:43:46.572][trace][5858][111] connect app, tcUrl=rtmp://127.0.0.1:19350/live, pageUrl=, swfUrl=, schema=rtmp, vhost=__defaultVhost__, port=19350, app=live, args=null
[2015-07-30 07:43:46.652][trace][5858][111] client identified, type=publish(FMLEPublish), stream_name=mjwvmpR1v9_h4dT2D4BVN_20150730_131321, duration=-1.00
[2015-07-30 07:43:46.652][trace][5858][111] out chunk size to 60000
[2015-07-30 07:43:46.652][trace][5858][111] source url=__defaultVhost__/live/mjwvmpR1v9_h4dT2D4BVN_20150730_131321, ip=127.0.0.1, cache=1, is_edge=0, source_id=-1[-1]
[2015-07-30 07:43:46.732][trace][5858][111] input chunk size to 60000
[2015-07-30 07:43:46.773][error][5858][111][32] send with writev failed. ret=1009(Broken pipe)
[2015-07-30 07:43:46.773][error][5858][111][32] send FCUnpublish response message failed. ret=1009(Broken pipe)
[2015-07-30 07:43:46.773][trace][5858][111] cleanup when unpublish
[2015-07-30 07:43:46.773][warn][5858][111][32] client disconnect peer. ret=1004
[2015-07-30 07:43:46.773][warn][5858][111][22] join thread failed. code=-1

**Comment by winlinvip** [comment]
```
[2015-07-30 07:43:46.773][error][5858][111][32] send with writev failed. ret=1009(Broken pipe)
```
FFMPEG close the connection.

**Comment by winlinvip** [comment]
Can u directly execute the ffmpeg command, for example:
```
 /home/voolastreamer/bin/ffmpeg -re -i rtmp://xxx.xxx.xxx.xxx:1935/staging_infinity_live/stream -vprofile baseline -acodec copy -vcodec copy -copyts -f flv -y rtmp://127.0.0.1:19350/live/stream
```

**Comment by gouravd** [comment]
When I run it directly, I get the following

WriteN, RTMP send error 10053 (136 bytes)B time=00:00:03.57 bitrate= 122.3kbits/s
WriteN, RTMP send error 10053 (41 bytes)
WriteN, RTMP send error 10038 (42 bytes)
av_interleaved_write_frame(): Operation not permitted
[flv @ 0000000004defce0] Failed to update header with correct duration.
[flv @ 0000000004defce0] Failed to update header with correct filesize.
frame=    5 fps=1.4 q=-1.0 Lsize=      61kB time=00:00:03.69 bitrate= 136.2kbits/s
video:19kB audio:43kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

**Comment by winlinvip** [comment]
Please use ffmpeg to dvr the stream to file:
```
/home/voolastreamer/bin/ffmpeg -re -i rtmp://xxx.xxx.xxx.xxx:1935/staging_infinity_live/stream -vprofile baseline -acodec copy -vcodec copy -copyts -f flv t.flv
```

**Comment by gouravd** [comment]
Writing to a local .flv works. I tested just now. I knew this works as I already have simillar line in my Nginx to save a copy in flv format.

Even in Nginx, restreaming from one App to another app is working.

But ffmpeg to SRS is not working. I had also tried using the -copyts

**Comment by winlinvip** [comment]
Can u provide the config of nginx-rtmp to replay this bug?
I am not familiar with nginx-rtmp.

**Comment by gouravd** [comment]
worker_processes  8;
rtmp_auto_push on;
rtmp_auto_push_reconnect 1s;

error_log logs/error.log crit;

events{
worker_connections  4000;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    access_log logs/access.log combined;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        location / {
	     proxy_pass       http://www.xxxxxxxxx.me;
            root   html;
            index  index.html index.htm;
        }
        
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

       
	 # This URL provides RTMP statistics in XML
        location /stat {
            rtmp_stat all;

            # Use this stylesheet to view XML as web page
            # in browser
            rtmp_stat_stylesheet stat.xsl;
        }

        location /stat.xsl {
            # XML stylesheet to view RTMP stats.
            # Copy stat.xsl wherever you want
            # and put the full directory path here
            root /home/voolastreamer/nginx/nginx-1.9.2/conf/;
        }

        location /staging_live_hls {
            # Serve HLS fragments
            types {
                application/vnd.apple.mpegurl m3u8;
                video/mp2t ts;
            }
            root /home/voolastreamer/Videos_staging/tmp;
            add_header Cache-Control no-cache;
		
	    # To avoid issues with cross-domain HTTP requests (e.g. during development)
            add_header Access-Control-Allow-Origin *;
        }

	 location /staging_flv {
            # Serve FLV files
            root /home/voolastreamer/Videos_staging;
        }

	 location /staging_mp4 {
            # Serve MP4 files
            root /home/voolastreamer/Videos_staging;
        }
    }
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;
	 ping 30s;
	 ping_timeout 20s;
	 buflen 100ms;

	 application staging_live_hls {
		live on;
		hls on;
		hls_path /home/voolastreamer/Videos_staging/tmp/staging_live_hls;
		hls_fragment 5s;
		hls_nested on;
		hls_playlist_length 15s;
	 }

	 #staging Infinity
        application staging_infinity_live {
		live on;
		interleave off;
	 	sync 10ms;
                        
		drop_idle_publisher 10s;
		idle_streams off;

		exec_push /home/voolastreamer/bin/ffmpeg -i rtmp:/xxx.xxx.xxx.xxx:1935/staging_infinity_live/$name -vprofile baseline -acodec copy -vcodec copy -copyts -f flv /home/voolastreamer/Videos_staging/staging_flv/$name.flv 2>>/home/voolastreamer/Videos_staging/staging_flv/$name-out.txt;
		#this is not working exec_push /home/voolastreamer/bin/ffmpeg -re -i rtmp:/xxx.xxx.xxx.xxx:1935/staging_infinity_live/$name -vprofile baseline -acodec copy -vcodec copy -f flv -y rtmp://xxx.xxx.xxx.xxx:19350/live/stream 2>>/home/voolastreamer/Videos_staging/staging_flv/$name-srs.txt
		exec_push /home/voolastreamer/bin/ffmpeg -re -i rtmp://xxx.xxx.xxx.xxx:1935/staging_infinity_live/$name -vprofile baseline -acodec copy -vcodec libx264 -f flv rtmp://xxx.xxx.xxx.xxx:1935/staging_live_hls/$name 2>>/home/voolastreamer/Videos_staging/staging_flv/$name-live-hls.txt;
        }
    }
}

**Comment by winlinvip** [comment]
Got it, I will try next week.

**Comment by winlinvip** [comment]
I try SRS 2.0.184, this bug fixed.

NGINX conf:
```
worker_processes  1;
daemon off;

events {
    worker_connections  1024;
}

rtmp {
    server {
        listen 1935;
        application live {
            live on;
            exec ffmpeg -re -i rtmp://127.0.0.1:1935/live/$name -vprofile baseline -acodec copy -vcodec copy -f flv -y rtmp://127.0.0.1:19350/live/$name;
        }
    }
}
```


SRS CONF:
```
max_connections     1000;
daemon              off;
srs_log_tank        console;
http_api {
    enabled         on;
    listen          1985;
}
http_server {
    enabled         on;
    listen          8080;
}
vhost __defaultVhost__ {
}
```

PUBLISH stream to nginx(1935) which will fork ffmpeg to push to SRS(19350):
```
ffmpeg -re -i doc/source.200kbps.768x320.flv -vcodec copy -acodec copy -f flv -y rtmp://127.0.0.1/live/livestream
```

The FFMPEG process forked by nginx-rtmp:
```
winlin:~ winlin$ ps aux|grep ffmpeg
winlin          17732   0.9  0.0  2518640   6000 s000  S+    6:11PM   0:00.41 ffmpeg -re -i rtmp://127.0.0.1:1935/live/livestream -vprofile baseline -acodec copy -vcodec copy -f flv -y rtmp://127.0.0.1:19350/live/livestream
```

**Comment by gouravd** [comment]
Thanks for your work on this. I will try and let you know
