### ISSUE TITLE
srs无法分片

### ISSUE THREAD

**Issue by itneste** [simple-rtmp-server/srs#472]
客户端使用srs.librtmp推送到srs 1.0release，客户端异常退出（其他原因崩溃，kill进程）后，再次打开客户端，会出现srs一直往一个.ts.tmp里面写数据，文件不断增大，且不再产生新的分片
服务器centos 6.7
srs 1.0release

**Comment by winlinvip** [comment]
SRS2.0已经发布alpha，请用SRS2。
