### ISSUE TITLE
srs_2.0对纯音频的流进行HLS切片失败。

### ISSUE THREAD

**Issue by niuxsh** [simple-rtmp-server/srs#478]
srs_2.0对纯音频的流进行HLS切片时，总是写同一个ts文件，没有持续生成新ts文件，并且用VLC单独播放这个切片也是没有声音的；

**Comment by winlinvip** [comment]
请提供重现步骤，配置和ffmpeg推流命令。

**Comment by niuxsh** [comment]
配置文件 conf/hls.conf 如下：
listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
    hls {
        enabled         on;
        hls_fragment    5;
        hls_window      60;
        hls_path        /tmp/srs/hls;
    }
}

启动命令：
./objs/srs -c conf/hls.conf

推流命令：
ffmpeg -re -i list_aac.flv -acodec copy -vn -f flv -y rtmp://192.168.145.111/live/wa
音频格式为aac，srs一直在重复写同一个ts文件。

**Comment by niuxsh** [comment]
我尝试着修复了一下这个bug（可能不完全正确），可以持续生成新的ts文件，但是用ffplay和VLC还是无法播放，ts的PMT里仍然有video信息。

**Comment by winlinvip** [comment]
请提供list_aac.flv文件，给个网盘地址吧。

**Comment by winlinvip** [comment]
你可以指定hls的编码：
```
hls {
    hls_vcodec vn;
    hls_acodec aac;
}
```

因为没有指定编码时，SRS最初是默认264+aac，因为服务器没法知道里面到底有没有视频和音频，得过一定时间才能猜到。

**Comment by niuxsh** [comment]
加上这样的配置就可以支持纯音频了， 不好意思，是我配置不对。如果要同时支持aac和MP3，应该怎么配置呢？ hls_acodec aac mp3; 这样吗？

**Comment by winlinvip** [comment]
应该用两个vhost。
