### ISSUE TITLE
How to loadbalance on a Origin - Edge configuration?

### ISSUE THREAD

**Issue by deluxor** [simple-rtmp-server/srs#482]
Hello friend can you please tell me how do you do loadbalancing on a ORIGIN -> EDGE configuration?

I think better way for now is to read from HTTP API the number of connected clients and redirect to the less used server, what do you think?

**Comment by winlinvip** [comment]
Exactly right.

The origin must be a cluster which know each other, please read #464
Or, there is a more smple solution: user config the max connection on origin and redirect to next when exceed.

Origin can use RTMP 302, defined by Adobe to let edge to redirect to another origin.
About the RTMP 302, please read #369
