### ISSUE TITLE
openssl 1.0.1f replacement

### ISSUE THREAD

**Issue by xiaoyur347** [simple-rtmp-server/srs#484]
SRS use openssl version 1.0.1f which has heartbleed bug. 
I suggest to update openssl to at least 1.0.1g as a replacement.

**Comment by winlinvip** [comment]
# @see http://www.openssl.org/news/secadv_20140407.txt
# Affected users should upgrade to OpenSSL 1.0.1g. Users unable to immediately
# upgrade can alternatively recompile OpenSSL with -DOPENSSL_NO_HEARTBEATS.

I will add this compile options.
