### ISSUE TITLE
缺少一个终止exec拉起进程及其子进程的机制

### ISSUE THREAD

**Issue by walkermi** [simple-rtmp-server/srs#486]
dev分支支持了exec/exec_publish: 当发布流时调用。如果exec执行的是一个不能主动exit的进程呢？貌似SRS没有kill机制，这个进程就会一直存在了。

可以参考nginx-rtmp，加一个kill机制，publish结束时，kill掉exec拉起的进程及他的所有子进程。
https://github.com/arut/nginx-rtmp-module/wiki/Exec-wrapper-in-bash

**Comment by winlinvip** [comment]
Why is it necessary to terminate this subprocess at the end of publishing? Where is it commonly used?

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
For example, when I publish, I start the script screen.sh, which contains a loop that captures an image every 30 seconds, as follows:


ffmpeg -i [url] -f image2 -vcodec mjpeg -vframes 1 -y /images/[stream].jpg 
sleep 30s


After the push is finished, how can I stop this loop?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
When the publication is stopped, SRS will terminate the child process started by exec.

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
Forgot, just looked at the code, it has been implemented now.

`TRANS_BY_GPT3`

**Comment by walkermi** [comment]
I also looked at the code, but I didn't understand it, haha.

After publishing, will it continuously loop and execute the specified command, or will it only be called once when an event occurs?

The called shell script should be written as 
for((;;)); do \
        ffmpeg -i [url] -f image2 -vcodec mjpeg -vframes 1 -y /images/[stream].jpg 
        sleep 30s
done


Or should it just be written as "Make sure to maintain the markdown structure.
ffmpeg -i [url] -f image2 -vcodec mjpeg -vframes 1 -y /images/[stream].jpg 
sleep 30s


If multiple command processes are started in the script, will SRS clean up all the processes and their child processes when exiting?

`TRANS_BY_GPT3`

**Comment by winlinvip** [comment]
It's all possible.
1. Start the process when publishing.
2. Check at regular intervals, if the process has exited, restart the process.
3. Stop when unpublishing.
Try it yourself and you'll know.

`TRANS_BY_GPT3`
