### ISSUE TITLE
编码器验证需求

### ISSUE THREAD

**Issue by MSG-maniac** [simple-rtmp-server/srs#487]
主要是怕恶意推送流，比如我某个rtmp地址被知道了。那么空闲阶段就可以直接用obs连上去推送了，请问是否能加一个验证，谢谢啦

**Comment by winlinvip** [comment]
Currently, the following verification mechanisms are provided:

- Security only allows streaming from certain IP addresses: [https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Security](https://github.com/simple-rtmp-server/srs/wiki/v2_EN_Security)
- HttpCallback can notify your system for verification: [https://github.com/simple-rtmp-server/srs/wiki/v1_EN_HTTPCallback](https://github.com/simple-rtmp-server/srs/wiki/v1_EN_HTTPCallback)

`TRANS_BY_GPT3`
