### ISSUE TITLE
srs2.0 release 下行并发测试

### ISSUE THREAD

**Issue by hx227** [simple-rtmp-server/srs#490]
pc配置：
酷睿i5 4570，内存双通道4G DDR3-1600，双千兆网卡
操作系统：
centos 6.6 final 内核版本 2.6.32-504
srs 版本：
 2.0 release alpha，使用默认配置文件，仅调整最大连接数至10000

测试工具：
srs 提供的 st-load

测试方法：
在千兆局域网内推送一路平均码流 300kbps 的流到srs，测试srs下行并发能力
两个网卡在两个不同的局域网

结果：
两个网卡都可以达到2000下行并发数，此时双网卡的数据发送量在每秒117MB达到千兆网饱和能力，此时cpu总占用率在15%~20%，但单核的占用率达到了50%以上。

问题：
srs能否动态调整cpu资源，避免出现单核心占用率偏高的情况？

**Comment by winlinvip** [comment]
在一台机器上部署一个集群，一个源站多个边缘。或者使用srs-dolphin或srs-sharp。
