### ISSUE TITLE
*BUG* Cannot consume stream from SRS (acting as an Origin server)

### ISSUE THREAD

**Issue by deluxor** [simple-rtmp-server/srs#493]
Friend, there's a bug (in my perspective) I know you wanted to simplify it but this way it will not work.
The problem is, if you have a wowza edge server consuming a stream from a SRS origin it will try the following:
```
Stream name: zzzzzz
App name: origin
```
The connection that wowza will try to do to SRS will be:
```
connect app, tcUrl=rtmp://SRS_SERVER_IP:1935/origin/_definst_, pageUrl=, swfUrl=WowzaProLiveRepeater, schema=rtmp, vhost=__defaultVhost__, port=1935, app=origin/_definst_, args=null
[2015-09-25 03:04:57.303][trace][1413][815] out chunk size to 60000
[2015-09-25 03:04:57.452][trace][1413][815] client identified, type=Play, stream_name=zzzzzz, duration=-1.00
[2015-09-25 03:04:57.452][trace][1413][815] source url=/origin/_definst_/zzzzzz, ip=WOWZA_EDGE_IP, cache=0, is_edge=0, source_id=-1[-1]
```
So the problem is it is adding the ```_definst_``` string to the app name, this way it will not find any stream because in the reality it is being broadcasted to ```origin/zzzzzz``` and not to ```origin/_definst_/zzzzzz```

So how can I solve this issue? Because I really need the wowza to consume from origin, wich source file do I need to edit to force remove the ```_definst_``` string from the app request?

Thank you.

**Comment by winlinvip** [comment]
You can push stream to: rtmp://SRS_SERVER_IP:1935/origin/_definst_/zzzzzz, where SRS will parsed to: 
vhost: `__defaultVhost__`
app: `origin/_definst_`
stream: `zzzzz`

Please try it.
