### ISSUE TITLE
devlope分支，今天最新update，几个bug提交。

### ISSUE THREAD

**Issue by walkermi** [simple-rtmp-server/srs#494]
develop branch最新代码，ingest文件并配置转码，转码功能无法启动。
conf文件如下：
listen              1935;
max_connections     1000;
vhost __defaultVhost__ {
    ingest livestream {
        enabled      on;
        input {
            type    file;
            url     /home/resource/xiaohuangrener.mp4;
        }
        ffmpeg      /usr/bin/ffmpeg;
        engine {
            enabled          on;
            vfilter {
            }
            vcodec          libx264;
            vbitrate        1000;
            vfps              25;
            vwidth          960;
            vheight         540;
            vthreads        12;
            vprofile        main;
            vpreset         medium;
            vparams {
            }
            output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
        }
    }
}

ingest同时转码不起作用？

**Comment by walkermi** [comment]
./configure --disable-all --with-ssl --with-hls --with-dvr --with-http-callback --with-http-api --with-stream-caster --with-ffmpeg --with-transcode --with-ingest --with-stat --with-research --with-librtmp

**Comment by winlinvip** [comment]
请使用2.0分支

**Comment by walkermi** [comment]
我只是测试学习，所以用开发分支，没有在生产环境使用，纯提bug而已。

**Comment by winlinvip** [comment]
请使用2.0分支。

**Comment by walkermi** [comment]
我想测试ngx_exec等新功能，2.0release分支就已经支持了？develop分支现在好多编译错误！
