### ISSUE TITLE
srs.librtmp导出的lib瘦身

### ISSUE THREAD

**Issue by backylee** [simple-rtmp-server/srs#495]
srs.librtmp配套srs版本：2.0

srs.librtmp导出后的文件瘦身，现在编译后不strip大小有3.1M+
-rw-r--r-- 1 root root 3162824 Sep 29 12:02 srs_librtmp.o
strip之后也有1.1M+有
-rw-r--r-- 1 root root 1110436 Sep 29 14:59 srs_librtmp.o

嵌入式设备使用，体积有点大。

**Comment by winlinvip** [comment]
我看看能不能关闭一些宏定义。

**Comment by winlinvip** [comment]
我把一些大的没有用的用下面的宏定义去掉了，减少了一半左右。
```
#if !defined(SRS_EXPORT_LIBRTMP)
```

你可以再看看哪些漏掉了的，core、kernel、protocol三个模块会导出到librtmp。
你可以自己把一些没有用的去掉，这样尺寸还可以继续减少。
