### ISSUE TITLE
Compiling on arm

### ISSUE THREAD

**Issue by paulashford1975** [simple-rtmp-server/srs#496]
Hi I'm compiling this on Arm iMX.6 board, however when I run the makefile I receive the following;

arm-linux-gnueabi-g++ -c -ansi -Wall -g -O0 -fPIC  -Isrc/core -Iobjs \
          -o objs/src/core/srs_core.o src/core/srs_core.cpp
In file included from src/core/srs_core.cpp:24:0:
src/core/srs_core.hpp:132:6: error: #error "for arm, only support glibc <= 2.15"
make[2]: *** [objs/src/core/srs_core.o] Error 1
make[2]: Leaving directory `/home/tmp/srs-develop/trunk'
make[1]: *** [server] Error 2
make[1]: Leaving directory `/home/tmp/srs-develop/trunk'

**Comment by deluxor** [comment]
Hello friend, you need glibc 2.15 at least to be able to build it, this was an hard to find bug that winlin found, so, you will need at least glibc 2.15 and gcc 4.6.3 other way you can't build it for ARM.

to check your versions run:
ldd -> to check the version off glibc
gcc -v -> to check the version of gcc

**Comment by paulashford1975** [comment]
Hi, thanks for the reply. I have checked the versions and there are newer than required? Results below.

architech@architech:/home/tmp/SRS-Ubuntu12-armv7cpu-1.0.30$ ldd --version
ldd (Ubuntu EGLIBC 2.19-0ubuntu6) 2.19
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
architech@architech:/home/tmp/SRS-Ubuntu12-armv7cpu-1.0.30$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/i686-linux-gnu/4.8/lto-wrapper
Target: i686-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-i386 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-i386 --with-arch-directory=i386 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-targets=all --enable-multiarch --disable-werror --with-arch-32=i686 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=i686-linux-gnu --host=i686-linux-gnu --target=i686-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04)

**Comment by deluxor** [comment]
Yeah thats the problem, you need the versions I said, not superior versions.

**Comment by paulashford1975** [comment]
ok I have managed to downgrade gcc to 4.3.4 struggling to downgrade libc to 2.15. I am trying to get this built to run as a build using Yocto which is currently running under a Ubuntu 14 build.

**Comment by winlinvip** [comment]
dup to #485
