### ISSUE TITLE
踢流的http-DELETE请求，如操作不慎可能导致SRS崩溃

### ISSUE THREAD

**Issue by haofz** [simple-rtmp-server/srs#497]
winlin你好:
       踢clents的是否，如果不慎使用如下操作：
        curl -v -X DELETE http://192.168.1.170:1985/api/v1/clients && echo ""      （**即不填写clientid）
      导致SRS崩溃，error日志如下：（**代码少了client参数变量的判断）
     [2015-09-30 10:51:21.345][trace][3475][152] HTTP DELETE http://192.168.1.7:1985/api/v1/clients/, content-length=-1
srs: src/app/srs_app_http_api.cpp:803: virtual int SrsGoApiClients::serve_http(ISrsHttpResponseWriter*, ISrsHttpMessage*): Assertion `client' failed.

另外请问：对于DELTE这种操作，有一定危险性，在安全性上有那些可以注意和考虑的吗？

**Comment by winlinvip** [comment]
应该返回错误码。
这种是bug，fix就好了。

**Comment by winlinvip** [comment]
fixed
