### ISSUE TITLE
on_dvr hook

### ISSUE THREAD

**Issue by icevl** [simple-rtmp-server/srs#498]
Hi!
Find some trouble with dvr hook. Look at this:

[2015-09-30 16:58:09.413][error][5924][113][9] http post on_dvr uri failed, ignored. client_id=109, url=http://myhooksdomain/myhook.php, request={"action":"on_dvr","client_id":109,"ip":"127.0.0.1","vhost":"hls","app":"live","stream":"cam34","cwd":"/usr/local/srs","file":"/mnt/data/records/cams/cam34/1443596268173.flv"}, response=1, code=200, ret=3008(Bad file descriptor)

I am response "1" (error code) not "0", but SRS still recording the stream, ignoring my hook response.
Thanks for advising!

**Comment by winlinvip** [comment]
`on_dvr` is used to call your system when dvr a piece completed.

What's the issue? What's your expect? What's your use scenario?

**Comment by icevl** [comment]
I need to deny recording for my specific cam. And before start recording i need to check permission in my hook-script: can i allow to start recording or no. 

I think that "on_dvr" started before recording. :)

**Comment by winlinvip** [comment]
Nop, the `on_dvr` is a dvr complete event.
For your scenario:
1. You can hook the `on_publish` event, which used to call your system when your cam publish stream to SRS
2. Verify the stream whether to record or not.
3. Call dvr api to start dvr when stream need to, read https://github.com/simple-rtmp-server/srs/wiki/v3_EN_HTTPApi#raw-dvr

**Comment by icevl** [comment]
This feature is available in SRS 3.0, but i dont know where i can get ready to be compiled SRS 3.0.
Thanks in advance.

**Comment by winlinvip** [comment]
GIT to checkout the develop branch(srs 3.0). Please google the git usage.
