### ISSUE TITLE
Question regarding HLS/HTTP

### ISSUE THREAD

**Issue by paulashford1975** [simple-rtmp-server/srs#501]
Hi, I have installed the pre-built version and want to enable HLS/HTTP. I am using the full.conf file but unable to get this work. Do i need to do a custom build, also you mention nginx, does this have to be installed separately? Basically I want all the features available in SRS. Thanks in advance.

**Comment by winlinvip** [comment]
Should never use full.conf, please follow the wiki step by step:
1. for HLS: https://github.com/simple-rtmp-server/srs/wiki/v1_EN_SampleHLS
1. for HTTP flv stream: https://github.com/simple-rtmp-server/srs/wiki/v2_EN_SampleHttpFlv
