### ISSUE TITLE
ingest如何配置虚拟直播多个视频文件？

### ISSUE THREAD

**Issue by winlinvip** [simple-rtmp-server/srs#55]
https://github.com/winlinvip/simple-rtmp-server/issues/55

**Comment by winlinvip** [comment]
You can start an ingest, such as a bash script, or a python script, or a program. This ingest can sequentially push multiple files into an RTMP stream, or switch files according to its own strategy.

`TRANS_BY_GPT3`

**Comment by NGbetrue** [comment]
Can you provide a simple demo or example for this feature? I didn't understand your response.

`TRANS_BY_GPT3`

**Comment by cqbc** [comment]
尝试了多种配置方式都不行

**Comment by cqbc** [comment]
I have tried multiple configuration methods but none of them work.
For example:
1>  input {
            type    file;
            url     /home/appops/dvr/__defaultVhost__/live/live-wangsugq0-201911151509.flv;
            url     /home/appops/dvr/__defaultVhost__/live/live-wangsugq0-201911211614.flv;
        }
2>   input {
            type    file;
            url     /home/appops/dvr/__defaultVhost__/live/live-wangsugq0-201911151509.flv /home/appops/dvr/__defaultVhost__/live/live-wangsugq0-201911211614.flv
       }

Please provide a demo example from the great author.

`TRANS_BY_GPT3`

**Comment by sky9639** [comment]
Can I use HTTP API to dynamically call the streaming?

`TRANS_BY_GPT3`

**Comment by xugcheng** [comment]
Just configure multiple ingets.

`TRANS_BY_GPT3`

**Comment by palmip** [comment]
ingest live2 {
        enabled      on;
        input {
            type    file;
            url     ./doc/2.mp4;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine sd1{
            enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd1;
        }
	engine sd2{
            enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd2;
        }
	        engine sd3{
        enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd3;
        }
    }

**Comment by palmip** [comment]
尝试下这种方案
ingest live2 {
        enabled      on;
        input {
            type    file;
            url     ./doc/2.mp4;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine sd1{
            enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd1;
        }
	engine sd2{
            enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd2;
        }
	        engine sd3{
        enabled          off;
         #   output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
             output rtmp://127.0.0.1:[port]/live/live2_sd3;
        }
    }

    ingest rtsp1{
        enabled      on;
        input {
            type    stream;
            #url     rtsp://admin:12345678@192.168.2.21:554/Streaming/Channels/501?transportmode=unicast;
	    url rtsp://192.168.91.41;
        }
        ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
           # output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/rtsp1;
	   output rtmp://127.0.0.1:[port]/live/rtsp1;
        }
    }

**Comment by chan-commits** [comment]
> Try this solution
> ingest live2 {
> enabled on;
> input {
> type file;
> url ./doc/2.mp4;
> }
> ffmpeg ./objs/ffmpeg/bin/ffmpeg;
> engine sd1{
> enabled off;
> # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> output rtmp://127.0.0.1:[port]/live/live2_sd1;
> }
> engine sd2{
> enabled off;
> # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> output rtmp://127.0.0.1:[port]/live/live2_sd2;
> }
> engine sd3{
> enabled off;
> # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> output rtmp://127.0.0.1:[port]/live/live2_sd3;
> }
> }
> 
> ```
> ingest rtsp1{
>     enabled      on;
>     input {
>         type    stream;
>         #url     rtsp://admin:12345678@192.168.2.21:554/Streaming/Channels/501?transportmode=unicast;
>     url rtsp://192.168.91.41;
>     }
>     ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
>     engine {
>         enabled          on;
>         perfile {
>             rtsp_transport tcp;
>         }
>         vcodec copy;
>         acodec copy;
>        # output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/rtsp1;
>    output rtmp://127.0.0.1:[port]/live/rtsp1;
>     }
> }
> ```

> May I ask how to add the -re parameter to ffmpeg?

`TRANS_BY_GPT3`

**Comment by sonny420** [comment]
> > Try this solution
> > ingest live2 {
> > enabled on;
> > input {
> > type file;
> > url ./doc/2.mp4;
> > }
> > ffmpeg ./objs/ffmpeg/bin/ffmpeg;
> > engine sd1{
> > enabled off;
> > # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> > output rtmp://127.0.0.1:[port]/live/live2_sd1;
> > }
> > engine sd2{
> > enabled off;
> > # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> > output rtmp://127.0.0.1:[port]/live/live2_sd2;
> > }
> > engine sd3{
> > enabled off;
> > # output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;
> > output rtmp://127.0.0.1:[port]/live/live2_sd3;
> > }
> > }
> > ```
> > ingest rtsp1{
> >     enabled      on;
> >     input {
> >         type    stream;
> >         #url     rtsp://admin:12345678@192.168.2.21:554/Streaming/Channels/501?transportmode=unicast;
> >     url rtsp://192.168.91.41;
> >     }
> >     ffmpeg      ./objs/ffmpeg/bin/ffmpeg;
> >     engine {
> >         enabled          on;
> >         perfile {
> >             rtsp_transport tcp;
> >         }
> >         vcodec copy;
> >         acodec copy;
> >        # output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/rtsp1;
> >    output rtmp://127.0.0.1:[port]/live/rtsp1;
> >     }
> > }
> > ```
> 
> May I ask how to add the `-re` parameter to ffmpeg?

> If you select "file" type, the `-re` parameter will be added automatically.

`TRANS_BY_GPT3`

**Comment by palmip** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    您好 我这边暂时咩有这个配置可以试试 那 加一下这 看看能否可以    vfilter {   re on    }或者可以参考下这个文档 https://blog.csdn.net/zjqlovell/article/details/47295783
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                475566936
                            
                    
                        
                            
                                    475566936@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2020年12月3日 13:36，SonnyTAT<notifications@github.com> 写道： 








尝试下这种方案

ingest live2 {

enabled on;

input {

type file;

url ./doc/2.mp4;

}

ffmpeg ./objs/ffmpeg/bin/ffmpeg;

engine sd1{

enabled off;

output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;

output rtmp://127.0.0.1:[port]/live/live2_sd1;

}

engine sd2{

enabled off;

output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;

output rtmp://127.0.0.1:[port]/live/live2_sd2;

}

engine sd3{

enabled off;

output rtmp://127.0.0.1:[port]/live?vhost=[vhost]/livestream;

output rtmp://127.0.0.1:[port]/live/live2_sd3;

}

}

ingest rtsp1{

    enabled      on;

    input {

        type    stream;

        #url     rtsp://admin:12345678@192.168.2.21:554/Streaming/Channels/501?transportmode=unicast;

    url rtsp://192.168.91.41;

    }

    ffmpeg      ./objs/ffmpeg/bin/ffmpeg;

    engine {

        enabled          on;

        perfile {

            rtsp_transport tcp;

        }

        vcodec copy;

        acodec copy;

       # output          rtmp://127.0.0.1:[port]/live?vhost=[vhost]/rtsp1;

   output rtmp://127.0.0.1:[port]/live/rtsp1;

    }

}





请问下如果加ffmpeg的-re参数应该如何加



type 選file 就會加-re了



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by guoronghui** [comment]
```

# The first pull stream starts
    ingest {
        enabled      on;
        input {
            type    stream;
            url     rtsp://10.0.0.11/tv1;
        }
        ffmpeg       ./objs/ffmpeg/bin/ffmpeg;
        engine {
            enabled          on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
            output          rtmp://127.0.0.1:[port]/live/tv1;
        }
    }    
    
# The first pull stream ends

# The second pull stream begins
    ingest tv2 {
        enabled      on;
        input {
            type    stream;
            url     rtsp://10.0.0.12/tv2;
        }
        ffmpeg       ./objs/ffmpeg/bin/ffmpeg;
        engine tv2 {
            enabled          on;
            perfile {
                rtsp_transport tcp;
            }
            vcodec copy;
            acodec copy;
            output          rtmp://127.0.0.1:[port]/live/tv2;
        }
    }    
    
# The second pull stream ends

# Multiple pull streams can refer to the above format

```

`TRANS_BY_GPT3`
